[package]
authors = ["Lennart Kämmle", "Peltoche <dev@halium.fr>"]
categories = ["parsing"]
description = "Ical/Vcard parser for Rust"
documentation = "https://docs.rs/caldata"
homepage = "https://github.com/lennart-k/caldata-rs"
keywords = ["ical", "vcard", "parser"]
license-file = "./LICENSE"
name = "caldata"
readme = "./README.md"
repository = "https://github.com/lennart-k/caldata-rs"
version = "0.16.2"
edition = "2024"

[profile.bench]
debug = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }

[dependencies]
thiserror = "2.0"
chrono-tz = { version = "0.10", optional = true }
chrono = { version = "0.4" }
regex = { version = "1.13" }
lazy_static = { version = "1.5" }
itertools = "0.15"
rkyv = { version = "0.8", optional = true }
derive_more = { version = "2.1", features = [
  "display",
  "from",
  "deref",
  "into",
] }
phf = { version = "0.14", features = ["macros"] }
vtimezones-rs = { version = "0.3" }
log = "0.4"

[dev-dependencies]
insta = { version = "1.48", features = ["filters"] }
similar-asserts = "2.0"
criterion = { version = "0.8", features = ["html_reports"] }
rstest = "0.26"

[[bench]]
name = "parse_benchmark"
harness = false

[features]
default = ["chrono-tz"]
chrono-tz = ["dep:chrono-tz"]
test = []
rkyv = ["dep:rkyv"]
bench = []

[lib]
doc = true
name = "caldata"
path = "src/lib.rs"
test = true
